//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.WebApi.PolicyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PolicyService.IPolicyService")]
    public interface IPolicyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/PolicyCalculate", ReplyAction="http://tempuri.org/IPolicyService/PolicyCalculateResponse")]
        int PolicyCalculate(string email, int carCost, int manufacturedYear, System.DateTime driverLicenseDate, System.DateTime birthDate, int enginePower);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/PolicyCalculate", ReplyAction="http://tempuri.org/IPolicyService/PolicyCalculateResponse")]
        System.Threading.Tasks.Task<int> PolicyCalculateAsync(string email, int carCost, int manufacturedYear, System.DateTime driverLicenseDate, System.DateTime birthDate, int enginePower);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/PolicyRegistration", ReplyAction="http://tempuri.org/IPolicyService/PolicyRegistrationResponse")]
        string PolicyRegistration(string email, int carCost, string carNumber, string carModel, int manufacturedYear, int enginePower);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/PolicyRegistration", ReplyAction="http://tempuri.org/IPolicyService/PolicyRegistrationResponse")]
        System.Threading.Tasks.Task<string> PolicyRegistrationAsync(string email, int carCost, string carNumber, string carModel, int manufacturedYear, int enginePower);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/GetPolicy", ReplyAction="http://tempuri.org/IPolicyService/GetPolicyResponse")]
        Insurance.BL.Models.Policy[] GetPolicy(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/GetPolicy", ReplyAction="http://tempuri.org/IPolicyService/GetPolicyResponse")]
        System.Threading.Tasks.Task<Insurance.BL.Models.Policy[]> GetPolicyAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPolicyServiceChannel : Insurance.WebApi.PolicyService.IPolicyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolicyServiceClient : System.ServiceModel.ClientBase<Insurance.WebApi.PolicyService.IPolicyService>, Insurance.WebApi.PolicyService.IPolicyService {
        
        public PolicyServiceClient() {
        }
        
        public PolicyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolicyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int PolicyCalculate(string email, int carCost, int manufacturedYear, System.DateTime driverLicenseDate, System.DateTime birthDate, int enginePower) {
            return base.Channel.PolicyCalculate(email, carCost, manufacturedYear, driverLicenseDate, birthDate, enginePower);
        }
        
        public System.Threading.Tasks.Task<int> PolicyCalculateAsync(string email, int carCost, int manufacturedYear, System.DateTime driverLicenseDate, System.DateTime birthDate, int enginePower) {
            return base.Channel.PolicyCalculateAsync(email, carCost, manufacturedYear, driverLicenseDate, birthDate, enginePower);
        }
        
        public string PolicyRegistration(string email, int carCost, string carNumber, string carModel, int manufacturedYear, int enginePower) {
            return base.Channel.PolicyRegistration(email, carCost, carNumber, carModel, manufacturedYear, enginePower);
        }
        
        public System.Threading.Tasks.Task<string> PolicyRegistrationAsync(string email, int carCost, string carNumber, string carModel, int manufacturedYear, int enginePower) {
            return base.Channel.PolicyRegistrationAsync(email, carCost, carNumber, carModel, manufacturedYear, enginePower);
        }
        
        public Insurance.BL.Models.Policy[] GetPolicy(string email) {
            return base.Channel.GetPolicy(email);
        }
        
        public System.Threading.Tasks.Task<Insurance.BL.Models.Policy[]> GetPolicyAsync(string email) {
            return base.Channel.GetPolicyAsync(email);
        }
    }
}
