// <auto-generated />
namespace MainRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class guid_policy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guid_policy));
        
        string IMigrationMetadata.Id
        {
            get { return "201910071516251_guid_policy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
